name: build

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/*"

jobs:
  build_cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        torch: [1.12.0, 1.13.0, 2.0.0]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # See: https://github.com/marketplace/actions/setup-miniconda
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          $channels: "conda-forge, pytorch"
          python-version: ${{ matrix['python-version'] }}
          use-mamba: true
      - name: Install PyTorch
        run: mamba install -c pytorch pytorch==${{matrix.torch}} cpuonly
      - name: Install Extras
        run: pip install -r requirements.txt
      - name : Install OpenBabel
        run: mamba install -c conda-forge openbabel
      - name: Install reduce
        run: mamba install -c speleo3 reduce
      #- name: Install Dev Dependencies
      #  run: pip install -r .requirements/dev.in
      - name: Run unit tests and generate coverage report
        run: python -m unittest discover -s tests -p "test_*.py"
      - name: Test notebook execution
        run: python -m unittest discover -s notebooks -p "test_*.py"
